### ISSUE TITLE
Backend URL needs to be updated 

### ISSUE THREAD

**Issue by krsnamara** [kiko-nunez/pizza-frontend#52]
With the new backend deployed we need to enter in the url for the fetch requests.
It is in the Main.js component. 
It needs to have the proper end point for each route.

**Comment by mohitmohlia** [comment]
Hello, can you assign this to me, and with the latest URL endpoints to update? Thanks

**Comment by keshari1arya** [comment]
@krsnamara all the hardcoded url strings needs to be moved to another file and can be used where needed as object ref. Also all API calls will be moved to a separate service file. Please feel free to assign me

**Comment by krsnamara** [comment]
> Hello, can you assign this to me, and with the latest URL endpoints to update? Thanks

Hey Mohit, thanks for the interest. I am going to give it to the owner of the repo. He has the new backend deployment endpoint.
